[package]
name = "binwalkpy"
version = "0.1.1"
edition = "2021"

[dependencies]
log = "0.4.22"
binwalk = "3.1.0"
env_logger = "0.11.5"
pyo3 = { version = "0.23.2", features = ["extension-module"] }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1