name: Build and Publish

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install maturin
      run: pip install maturin

    - name: Build the package
      run: maturin build --release --out dist/

    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: linux-wheel
        path: dist/*.whl

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install maturin
      run: pip install maturin

    - name: Build the package
      run: maturin build --release --out dist/

    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: windows-wheel
        path: dist/*.whl

  publish:
    if: github.ref == 'refs/heads/main'
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install maturin
      run: pip install maturin

    - name: Download Linux wheel
      uses: actions/download-artifact@v2
      with:
        name: linux-wheel
        path: dist/

    - name: Download Windows wheel
      uses: actions/download-artifact@v2
      with:
        name: windows-wheel
        path: dist/

    - name: Publish to PyPI
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_KEY }}
      run: maturin publish --skip-existing dist/*.whl